"""created table user

Revision ID: a55b6ebc9129
Revises: 414733370477
Create Date: 2022-03-08 14:49:08.060974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55b6ebc9129'
down_revision = '414733370477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
