"""changed nullable from false to true

Revision ID: fac7980f57ce
Revises: e23f42685a9e
Create Date: 2022-03-07 17:43:20.608193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac7980f57ce'
down_revision = 'e23f42685a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
